twitt/twitter/config/routes.rb
Rails.application.routes.draw do
  resources :homes

   root 'homes#index'
   get '/auth/:provider/callback', to: 'sessions#create'

end

twitt/twitter/app/models/home.rb
class Home < ActiveRecord::Base
end

twitt/twitter/app/models/user.rb
class User < ActiveRecord::Base
	 def self.find_or_create_from_auth_hash(auth_hash)
       user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
       user.update(
       	name: auth_hash.info.name,
       	profile_image: auth_hash.info.image,
        token: auth_hash.credentials.token,
        secret: auth_hash.credentials.secret
       	) 
       user
    end      	  
end

twitt/twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	 @current_user ||= User.find(session[:used_id]) if session[:used_id]
  end	
   
   helper_method :current_user 

end

twitt/twitter/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:User, :Body)
    end
end

twitt/twitter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id]= @user.id
    #self.current_user = @user
    redirect_to root_path
  end



  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

twitt/twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

twitt/twitter/app/helpers/homes_helper.rb
module HomesHelper
end

twitt/twitter/app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :User %><br>
    <%= f.text_field :User %>
  </div>
  <div class="field">
    <%= f.label :Body %><br>
    <%= f.text_field :Body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitt/twitter/app/views/homes/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

twitt/twitter/app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "text-center">
<h1>Welcome to my Home Page</h1>
<p>Have a nice day</p>
</div>

<h1>List Tweet</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.User %></td>
        <td><%= home.Body %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_home_path %>

twitt/twitter/app/views/homes/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

twitt/twitter/app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @home.User %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.Body %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

twitt/twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


 <!--goto maxcdn bootstrap w3schools-->

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    
      <div class="navbar-header">

   <h1><%= link_to root_path do%>Bombay-cast<% end %></h1>
</div>

    
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        </ul>
        <form class="navbar-form navbar-left" role="search">
      </form> 
 <ul class="nav navbar-nav navbar-right">


<% if current_user %>
      <li>= "navbar-text navbar-right">Signed in as<%= link_to current_user.name %></li>
          <li> <%= image_tag(@auth['info']['image'], width: '50', height: '50')%></li>
      <li><%= link_to "Yaas!!!", 'sign_out', method: :delete %></ li>
    <% else %> 
  <li><%= link_to "auth/twitter" do %><%= image_tag('twitter.png', width: '40', height: '40')%> <% end %></li>  
 <% end %>


</div>

    </div>

     </nav>

      <div class="container">

     <%= yield %>

   </div>

</body>
</html>